### ISSUE TITLE
about Gaussian Dataset setting

### ISSUE THREAD

**Issue by danboardxu** [czifan/DeepGamblers.pytorch#2]
could u share the toy dataset details&code?

**Comment by czifan** [comment]
Hello, I have rechecked the code and found that I lost this part of the code, so I rewrote a generated data program, please see "generate_gaus.py". 
Note:  The code generates 2D Gaussian data from two 1-D Gaussian distribution, since no method was found in Numpy to generate this directly. If you have a better method to do that, I hope you can share it~

**Comment by danboardxu** [comment]
thank u for ur sharing
